---
engines:
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/**/*
