---
engines:
  radon:
    enabled: true
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/**/*
- vendor/**
