---
engines:
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
        python:
          mass_threshold: 40
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/**/*
